name: Feature request (Language Support for Java)
description: Suggest a new feature or improvement for Language Support for Java
title: "[Feature]: "
labels: ["feature"]
assignees: []
type: feature
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: Describe the problem
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Describe your proposed solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Alternative solutions or features
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
      placeholder: Any other context
